{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","errorLabels":["TransientTransactionError"]},"level":"error","message":"uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\nMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/msadoon/Documents/Projects/vidly/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:180:13)\n    at Connection.<anonymous> (/Users/msadoon/Documents/Projects/vidly/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:272:13)\n    at Connection.emit (events.js:180:13)\n    at Socket.<anonymous> (/Users/msadoon/Documents/Projects/vidly/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:272:13)\n    at Socket.emit (events.js:180:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:178:19)","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/msadoon/Documents/Projects/vidly/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:180:13)\n    at Connection.<anonymous> (/Users/msadoon/Documents/Projects/vidly/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:272:13)\n    at Connection.emit (events.js:180:13)\n    at Socket.<anonymous> (/Users/msadoon/Documents/Projects/vidly/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:272:13)\n    at Socket.emit (events.js:180:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:178:19)","exception":true,"date":"Tue Jul 24 2018 23:30:07 GMT+0100 (BST)","process":{"pid":16658,"uid":1360004952,"gid":864334757,"cwd":"/Users/msadoon/Documents/Projects/vidly","execPath":"/usr/local/Cellar/node/9.11.1/bin/node","version":"v9.11.1","argv":["/usr/local/Cellar/node/9.11.1/bin/node","/Users/msadoon/Documents/Projects/vidly/index.js"],"memoryUsage":{"rss":95444992,"heapTotal":91660288,"heapUsed":55307144,"external":18039593}},"os":{"loadavg":[2.39990234375,2.0556640625,1.9814453125],"uptime":174505},"trace":[{"column":11,"file":"/Users/msadoon/Documents/Projects/vidly/node_modules/mongodb-core/lib/topologies/server.js","function":null,"line":562,"method":null,"native":false},{"column":13,"file":"events.js","function":"Pool.emit","line":180,"method":"emit","native":false},{"column":12,"file":"/Users/msadoon/Documents/Projects/vidly/node_modules/mongodb-core/lib/connection/pool.js","function":null,"line":316,"method":null,"native":false},{"column":13,"file":"events.js","function":"Object.onceWrapper","line":272,"method":"onceWrapper","native":false},{"column":13,"file":"events.js","function":"Connection.emit","line":180,"method":"emit","native":false},{"column":50,"file":"/Users/msadoon/Documents/Projects/vidly/node_modules/mongodb-core/lib/connection/connection.js","function":null,"line":245,"method":null,"native":false},{"column":13,"file":"events.js","function":"Object.onceWrapper","line":272,"method":"onceWrapper","native":false},{"column":13,"file":"events.js","function":"Socket.emit","line":180,"method":"emit","native":false},{"column":8,"file":"internal/streams/destroy.js","function":"emitErrorNT","line":64,"method":null,"native":false},{"column":19,"file":"internal/process/next_tick.js","function":"process._tickCallback","line":178,"method":"_tickCallback","native":false}]}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","errorLabels":["TransientTransactionError"]},"level":"error","message":"uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\nMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/msadoon/Documents/Projects/vidly/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:180:13)\n    at Connection.<anonymous> (/Users/msadoon/Documents/Projects/vidly/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:272:13)\n    at Connection.emit (events.js:180:13)\n    at Socket.<anonymous> (/Users/msadoon/Documents/Projects/vidly/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:272:13)\n    at Socket.emit (events.js:180:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:178:19)","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/msadoon/Documents/Projects/vidly/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:180:13)\n    at Connection.<anonymous> (/Users/msadoon/Documents/Projects/vidly/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:272:13)\n    at Connection.emit (events.js:180:13)\n    at Socket.<anonymous> (/Users/msadoon/Documents/Projects/vidly/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:272:13)\n    at Socket.emit (events.js:180:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:178:19)","exception":true,"date":"Tue Jul 24 2018 23:46:38 GMT+0100 (BST)","process":{"pid":16806,"uid":1360004952,"gid":864334757,"cwd":"/Users/msadoon/Documents/Projects/vidly","execPath":"/usr/local/Cellar/node/9.11.1/bin/node","version":"v9.11.1","argv":["/usr/local/Cellar/node/9.11.1/bin/node","/Users/msadoon/Documents/Projects/vidly/index.js"],"memoryUsage":{"rss":96047104,"heapTotal":92184576,"heapUsed":55404240,"external":17974413}},"os":{"loadavg":[2.29638671875,2.0908203125,1.9755859375],"uptime":175496},"trace":[{"column":11,"file":"/Users/msadoon/Documents/Projects/vidly/node_modules/mongodb-core/lib/topologies/server.js","function":null,"line":562,"method":null,"native":false},{"column":13,"file":"events.js","function":"Pool.emit","line":180,"method":"emit","native":false},{"column":12,"file":"/Users/msadoon/Documents/Projects/vidly/node_modules/mongodb-core/lib/connection/pool.js","function":null,"line":316,"method":null,"native":false},{"column":13,"file":"events.js","function":"Object.onceWrapper","line":272,"method":"onceWrapper","native":false},{"column":13,"file":"events.js","function":"Connection.emit","line":180,"method":"emit","native":false},{"column":50,"file":"/Users/msadoon/Documents/Projects/vidly/node_modules/mongodb-core/lib/connection/connection.js","function":null,"line":245,"method":null,"native":false},{"column":13,"file":"events.js","function":"Object.onceWrapper","line":272,"method":"onceWrapper","native":false},{"column":13,"file":"events.js","function":"Socket.emit","line":180,"method":"emit","native":false},{"column":8,"file":"internal/streams/destroy.js","function":"emitErrorNT","line":64,"method":null,"native":false},{"column":19,"file":"internal/process/next_tick.js","function":"process._tickCallback","line":178,"method":"_tickCallback","native":false}]}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","errorLabels":["TransientTransactionError"]},"level":"error","message":"uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\nMongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/msadoon/Documents/Projects/vidly/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:180:13)\n    at Connection.<anonymous> (/Users/msadoon/Documents/Projects/vidly/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:272:13)\n    at Connection.emit (events.js:180:13)\n    at Socket.<anonymous> (/Users/msadoon/Documents/Projects/vidly/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:272:13)\n    at Socket.emit (events.js:180:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:178:19)","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/msadoon/Documents/Projects/vidly/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:180:13)\n    at Connection.<anonymous> (/Users/msadoon/Documents/Projects/vidly/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:272:13)\n    at Connection.emit (events.js:180:13)\n    at Socket.<anonymous> (/Users/msadoon/Documents/Projects/vidly/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:272:13)\n    at Socket.emit (events.js:180:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:178:19)","exception":true,"date":"Tue Jul 24 2018 23:46:38 GMT+0100 (BST)","process":{"pid":16806,"uid":1360004952,"gid":864334757,"cwd":"/Users/msadoon/Documents/Projects/vidly","execPath":"/usr/local/Cellar/node/9.11.1/bin/node","version":"v9.11.1","argv":["/usr/local/Cellar/node/9.11.1/bin/node","/Users/msadoon/Documents/Projects/vidly/index.js"],"memoryUsage":{"rss":96047104,"heapTotal":92184576,"heapUsed":55404240,"external":17974413}},"os":{"loadavg":[2.29638671875,2.0908203125,1.9755859375],"uptime":175496},"trace":[{"column":11,"file":"/Users/msadoon/Documents/Projects/vidly/node_modules/mongodb-core/lib/topologies/server.js","function":null,"line":562,"method":null,"native":false},{"column":13,"file":"events.js","function":"Pool.emit","line":180,"method":"emit","native":false},{"column":12,"file":"/Users/msadoon/Documents/Projects/vidly/node_modules/mongodb-core/lib/connection/pool.js","function":null,"line":316,"method":null,"native":false},{"column":13,"file":"events.js","function":"Object.onceWrapper","line":272,"method":"onceWrapper","native":false},{"column":13,"file":"events.js","function":"Connection.emit","line":180,"method":"emit","native":false},{"column":50,"file":"/Users/msadoon/Documents/Projects/vidly/node_modules/mongodb-core/lib/connection/connection.js","function":null,"line":245,"method":null,"native":false},{"column":13,"file":"events.js","function":"Object.onceWrapper","line":272,"method":"onceWrapper","native":false},{"column":13,"file":"events.js","function":"Socket.emit","line":180,"method":"emit","native":false},{"column":8,"file":"internal/streams/destroy.js","function":"emitErrorNT","line":64,"method":null,"native":false},{"column":19,"file":"internal/process/next_tick.js","function":"process._tickCallback","line":178,"method":"_tickCallback","native":false}]}
